export const groupData = [
    { ItrLabel: '1.1-FBT Contribution', GstCode:'BAS Excluded' },
    { ItrLabel: '1.1-Gross distribution from trusts', GstCode: 'GST Free Expenses' },
    { ItrLabel: '1.1-Gross Income', GstCode: 'GST Free Income' },
    { ItrLabel: '1.1-Gross Interest', GstCode: 'GST on Expenses' },
    { ItrLabel: '1.1-Total Dividends', GstCode: 'GST on Income' },
    { ItrLabel: '1.9-Gov Subsidies' },
    { ItrLabel: '2.1 - Opening Stock' },
    { ItrLabel: '2.2-Cost of Sales' },
    { ItrLabel: '2.3 - Closing Stock' },
    { ItrLabel: '2.4-40-880 Deduction' },
    { ItrLabel: '2.4-Contractor fees' },
    { ItrLabel: '2.4-Superannuation expense' },
    { ItrLabel: '2.5-Interest paid Australia' },
    { ItrLabel: '2.5-Interest paid Overseas' },
    { ItrLabel: '2.5-Rent' },
    { ItrLabel: '5.1-Depreciation' },
    { ItrLabel: '2.6-Lease payments Australia' },
    { ItrLabel: '2.6-Lease payments Overseas' },
    { ItrLabel: '5.1-Depreciation' },
    { ItrLabel: '5.2-MV Expenses' },
    { ItrLabel: '5.3-Repair and Maintenance' },
    { ItrLabel: '9.1-All Other Expenses' },
    { ItrLabel: '9.3-Director Fees' },
    { ItrLabel: '9.2-Non Deductible Expenses' }
];